apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clinicflow-staging
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Bludive-Devops-Platform/clinicflow-gitops.git
    targetRevision: HEAD
    path: charts/clinicflow
    helm:
      valueFiles:
        - ../../environments/staging/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: clinicflow-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
